// This file has been automatically generated by Jinja2 via the
// script /Users/almico/projects/convolutions-rs/scripts/generate_tests.py.
// Please do not change this file by hand.
#[allow(unused_imports)]
use convolutions_rs::convolutions::*;
#[allow(unused_imports)]
use convolutions_rs::transposed_convolutions::*;
#[allow(unused_imports)]
use convolutions_rs::Padding;
#[allow(unused_imports)]
use ndarray::{array, Array, Array3, Array4, Dimension};
use ndarray_rand::rand_distr::Normal;
use ndarray_rand::RandomExt;
use std::time::Instant;

#[test]
fn test_py_implementation_random_arrays_conv2d_transpose() {

    let input = Array::random((128, 128, 128), Normal::new(0.0, 1.0).unwrap());
    let w = Array::random((128, 3, 5, 5), Normal::new(0.0, 1.0).unwrap());
    let l = TransposedConvolutionLayer::new_tf(w,None, 2, Padding::Same);
    
    let now_new = Instant::now();
    let res = l.transposed_convolve(&input);
    let elapsed_conv = now_new.elapsed();
    println!("Elapsed: {:.2?}", elapsed_conv);
    println!("{:?}", res.shape());

}
